### ISSUE TITLE
Passing: GPM MERGIR

### ISSUE THREAD

**Issue by ranchodeluxe** [NASA-IMPACT/veda-pforge-job-runner#17] opened 2024-01-04 23:51 UTC
https://github.com/pangeo-forge/staged-recipes/pull/260
- [x] Runs on `LocalDirectBakery` using prune option

```
pangeo-forge-runner bake \
    --repo=https://github.com/developmentseed/pangeo-forge-staging \
    --ref="gpm_mergir_gcorradini" \
    --Bake.feedstock_subdir="recipes/gpm_mergir" \
    -f config.py 
```

- [x] Runs on `LocalDirectBakery` for all timesteps

```
pangeo-forge-runner bake \
    --repo=https://github.com/developmentseed/pangeo-forge-staging \
    --ref="gpm_mergir_gcorradini" \
    --Bake.feedstock_subdir="recipes/gpm_mergir" \
    -f config.py 
```

- [x] Runs on `FlinkOperatorBakery` for prune option

```
curl -X POST \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
-H "Authorization: token blablah" \
https://api.github.com/repos/NASA-IMPACT/veda-pforge-job-runner/actions/workflows/job-runner.yaml/dispatches \
-d '{"ref":"main", "inputs":{"repo":"https://github.com/developmentseed/pangeo-forge-staging","ref":"gpm_mergir_gcorradini","prune":"1","feedstock_subdir": "recipes/gpm_mergir"}}'
```

- [x] Runs on `FlinkOperatorBakery` for all timesteps

```
curl -X POST \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
-H "Authorization: token blablah" \
https://api.github.com/repos/NASA-IMPACT/veda-pforge-job-runner/actions/workflows/job-runner.yaml/dispatches \
-d '{"ref":"main", "inputs":{"repo":"https://github.com/developmentseed/pangeo-forge-staging","ref":"gpm_mergir_gcorradini","prune":"0","feedstock_subdir": "recipes/gpm_mergir"}}'
```

**Comment by abarciauskas-bgse** [comment] 2024-01-17 20:04
@ranchodeluxe the target dataset was intended to be GPM IMERG so I have opened a new (draft) PR https://github.com/pangeo-forge/staged-recipes/pull/264 which thankfully has fewer files (8,461). Should we update this issue with that collection or close this and open a new issue?

**Comment by ranchodeluxe** [comment] 2024-01-18 18:42
> @ranchodeluxe the target dataset was intended to be GPM IMERG so I have opened a new (draft) PR [pangeo-forge/staged-recipes#264](https://github.com/pangeo-forge/staged-recipes/pull/264) which thankfully has fewer files (8,461). Should we update this issue with that collection or close this and open a new issue?

Thanks for doing that 🥳  I'll update this ticket to point to your new PR branch and test it out locally and on Flink

**Comment by ranchodeluxe** [comment] 2024-01-25 23:19
@abarciauskas-bgse: I was creating a PR for https://github.com/pangeo-forge/staged-recipes/pull/264 to fold in the changes on `pangeo-forge-recipe` that just merged. I thought I'd write a new validator/tester function to make sure the reference file that `ConsolidateMetadata` outputs works as expected. [Here is my updated recipe](https://github.com/developmentseed/pangeo-forge-staging/blob/gpm_imerg_gcorradini/recipes/gpm_imerg/recipe.py)

Outcomes:

0. we can read the reference file fine with `zarr.open_conslidated`, but...
1. `xr.open_dataset(..., consolidated=True)` should work too but doesn't

Filing a ticket

**Comment by ranchodeluxe** [comment] 2024-01-25 23:20
> @abarciauskas-bgse: I was creating a PR for [pangeo-forge/staged-recipes#264](https://github.com/pangeo-forge/staged-recipes/pull/264) to fold in the changes on `pangeo-forge-recipe` that just merged. I thought I'd write a new validator/tester function to make sure the reference file that `ConsolidateMetadata` outputs works as expected. [Here is my updated recipe](https://github.com/developmentseed/pangeo-forge-staging/blob/gpm_imerg_gcorradini/recipes/gpm_imerg/recipe.py)
> 
> Outcomes:
> 
>     0. we can read the reference file fine with `zarr.open_conslidated`, but...
> 
>     1. `xr.open_dataset(..., consolidated=True)` should work too but doesn't
> 
> 
> Filing a ticket

I guess the good news is this mostly works

**Comment by ranchodeluxe** [comment] 2024-01-25 23:32
ticket: https://github.com/pangeo-forge/pangeo-forge-recipes/issues/675

**Comment by ranchodeluxe** [comment] 2024-01-27 15:06
calling this a success and changing to passing since I've run multiple years on Flink and locally to prove it works. There still seem to be holes for some datasets that result in 404(s) so we'll have to figure out where the hole are incrementally

**Comment by ranchodeluxe** [comment] 2024-01-27 15:48
> calling this a success and changing to passing since I've run multiple years on Flink and locally to prove it works. There still seem to be holes for some datasets that result in 404(s) so we'll have to figure out where the holes are incrementally, work around them and tell folks upstream

Seems we have holes after ~15 years of data (which makes sense based on history of IMERG and TRMM). 

This run can do all 14 years in ~5 minutes with `parallelism:5`: https://github.com/NASA-IMPACT/veda-pforge-job-runner/actions/runs/7679542574

**Comment by abarciauskas-bgse** [comment] 2024-01-29 16:52
>This run can do all 14 years in ~9 minutes with parallelism:5: https://github.com/NASA-IMPACT/veda-pforge-job-runner/actions/runs/7679542574

That's awesome!!! 🥳

**Comment by ranchodeluxe** [comment] 2024-02-04 14:44
@abarciauskas-bgse: profile of `LocalDirectRunner.num_workers=1` on JH with this GPM IMERGE recipe. So same memory pattern locally (just not as drastic as TRMM) and possibly is able to run on Flink b/c the current per-worker resourcing is so large that it just works. More to look into. About to run LEAP (which is only `StoreToZarr`) and definitely will have the same pattern. I have ideas on how to isolate the issue if it is a memory leak and will create at ticket

<img width="1770" alt="Screen Shot 2024-02-04 at 6 39 13 AM" src="https://github.com/NASA-IMPACT/veda-pforge-job-runner/assets/208859/a467ec43-1457-4a3c-ae4c-cd62c9384f14">

**Comment by ranchodeluxe** [comment] 2024-02-05 14:54
ticket: https://github.com/NASA-IMPACT/veda-pforge-job-runner/issues/32

**Closed** 2024-05-10 16:58 UTC
Labels: documentation
